apps/fidouche/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'fidouche.views',
    url(r'^$', 'financial_dashboard', {}, name='financial_dashboard'),

    url(r'^(?P<year>\d{4})/', 'gigs_by_year', {}, name='gigs_by_year'),
    url(r'^gigs/year-over-year', 'gigs_year_over_year', {}, name='gigs_year_over_year'),
    url(r'^gigs/(?P<gig_id>\d+)/$', 'gig_finances', {}, name='gig_finances'),
    url(r'^gigs/view/(?P<gig_id>\d+)/$', 'gig_finances_view', {}, name='gig_finances_view'),

    url(r'^tours/$', 'tour_list', {}, name='tour_list'),
    url(r'^tours/(?P<tour_id>\d+)/$', 'tour_detail', {}, name='tour_detail'),

    url(r'^expenses/year/(?P<year>\d{4})/', 'expenses_list', {}, name='expenses_list'),
    url(r'^expenses/$', 'all_expenses_list', {}, name='all_expenses_list'),
    url(r'^expenses/(?P<expense_id>\d+)/$', 'expense_details', {}, name='expense_details'),
    url(r'^expenses/create/$', 'expense_create', {}, name='expense_create'),
    url(r'^expenses/delete/(?P<expense_id>\d+)/$', 'expense_delete', {}, name='expense_delete'),

    url(r'^income/year/(?P<year>\d{4})/', 'income_list', {}, name='income_list'),
    url(r'^income/$', 'all_income_list', {}, name='all_income_list'),
    url(r'^income/(?P<income_id>\d+)/$', 'income_details', {}, name='income_details'),
    url(r'^income/create/$', 'income_create', {}, name='income_create'),
    url(r'^income/delete/(?P<income_id>\d+)/$', 'income_delete', {}, name='income_delete'),

    url(r'^reports/$', 'finance_reports', {}, name='finance_reports'),
    url(r'^tax-reports/$', 'tax_reports', {}, name='tax_reports'),
    url(r'^member-payments/(?P<member_id>\d+)$', 'member_payments', {}, name='member_payments'),
    url(r'^sub-payments/(?P<sub_id>\d+)$', 'sub_payments', {}, name='sub_payments'),
    url(r'^vendor-payments/(?P<vendor_id>\d+)$', 'vendor_payments', {}, name='vendor_payments'),
    url(r'^production-payments/(?P<company_id>\d+)$', 'production_payments', {}, name='production_payments'),

    url(r'^map/$', 'venue_map', {}, name='venue_map'),
    url(r'^map-data/$', 'venue_map_data', {}, name='venue_map_data'),
)

urls.py
from django.conf.urls import patterns, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('marketing.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^members/', include('members.urls')),
    (r'^shows/', include('shows.urls')),
    (r'^songs/', include('songs.urls')),
    (r'^photos/', include('media.urls')),
    (r'^fidouche/', include('fidouche.urls')),
    (r'^setter/', include('setter.urls')),
    (r'^downloads/', 'media.views.downloads'),
    (r'^behind-the-music/', 'media.views.behind_the_music'),
    (r'^media/upload/', 'media.views.upload'),
    # Legacy redirects
    (r'^upcoming-shows/', RedirectView.as_view(url='/shows', permanent=True)),
    (r'^past-shows/', RedirectView.as_view(url='/shows/past', permanent=True)),
    (r'^song-list/', RedirectView.as_view(url='/songs', permanent=True)),
    (r'^news-press/', RedirectView.as_view(url='/', permanent=True)),
    (r'^quotes/', RedirectView.as_view(url='/about#quotes', permanent=True)),
    (r'^catalog/', RedirectView.as_view(url='http://v2.foreverland.com/catalog/', permanent=True)),
    (r'^theworks/', RedirectView.as_view(url='http://v2.foreverland.com/theworks/', permanent=True)),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^404/$', 'django.views.defaults.page_not_found'),
        (r'^500/$', 'django.views.defaults.server_error'),
    )

apps/fidouche/models.py
from django.db import models

from localflavor.us.models import PhoneNumberField, USStateField

from members.models import Member, Sub
from shows.models import Show, Tour


class Payment(models.Model):
    show = models.ForeignKey(Show, related_name="payment", null=True)
    member = models.ForeignKey(Member, related_name="payment", null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        unique_together = (('show', 'member'),)
        ordering = ['show__date']

    def __unicode__(self):
        payee = str(self.member.display_first) if self.member else '',
        show = str(self.show.venue) if self.show.venue else '',
        date = self.show.date.strftime('%m/%d/%y') if self.show else '',
        return '%s for %s on %s' % (payee[0], show[0], date[0])


class SubPayment(models.Model):
    show = models.ForeignKey(Show, related_name="subpayment", blank=True, null=True)
    sub = models.ForeignKey(Sub, related_name="sub", blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        unique_together = (('show', 'sub'),)

    def __unicode__(self):
        return '%s for %s on %s' % (self.sub.first_name, self.show.venue, self.show.date.strftime('%m/%d/%y'))


class Payee(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = USStateField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(verbose_name="Zip", max_length=20, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)
    ssn = models.CharField(verbose_name="SSN#", max_length=16, blank=True, null=True)

    def __unicode__(self):
        return self.name


class TaxExpenseCategory(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Tax Expense Categories"


class ExpenseCategory(models.Model):
    category = models.CharField(max_length=100, blank=True, null=True)
    tax_category = models.ForeignKey(TaxExpenseCategory, related_name="expense_category", blank=True, null=True)

    def __unicode__(self):
        return self.category

    class Meta:
        verbose_name_plural = "Expense Categories"


class Expense(models.Model):

    show = models.ForeignKey(Show, related_name="expense", blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    payee = models.ForeignKey(Payee, related_name="expense", blank=True, null=True)
    new_category = models.ForeignKey(ExpenseCategory, related_name="expense_category", blank=True, null=True, verbose_name="Category")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    check_no = models.CharField(max_length=100, blank=True, null=True, verbose_name="Check #")
    notes = models.TextField(blank=True, null=True)
    receipt_img = models.FileField(upload_to="receipts/", blank=True, null=True)

    @property
    def filetype(self):
        if self.receipt_img:
            return self.receipt_img.name[-3:]
        else:
            return None

    def __unicode__(self):
        safedate = ''
        if self.date:
            safedate = self.date.strftime('%m/%d/%y') + ', '
        return '%s$%s to %s' % (safedate, self.amount, self.payee)


class TourExpense(models.Model):

    tour = models.ForeignKey(Tour, blank=True, null=True)
    date = models.DateField(blank=True, null=True, verbose_name="Expense Date")
    payee = models.ForeignKey(Payee, blank=True, null=True)
    category = models.ForeignKey(ExpenseCategory, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    check_no = models.CharField(max_length=100, blank=True, null=True, verbose_name="Check #")
    notes = models.TextField(blank=True, null=True)
    receipt_img = models.FileField(upload_to="receipts/", blank=True, null=True)

    @property
    def filetype(self):
        if self.receipt_img:
            return self.receipt_img.name[-3:]
        else:
            return None

    @property
    def new_category(self):
        return self.category

    def __unicode__(self):
        safedate = ''
        if self.date:
            safedate = self.date.strftime('%m/%d/%y') + ', '
        return '%s$%s to %s' % (safedate, self.amount, self.payee)


class Income(models.Model):

    date = models.DateField(blank=True, null=True)
    payer = models.CharField(blank=True, null=True, max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    check_no = models.CharField(max_length=100, blank=True, null=True, verbose_name="Check #")
    notes = models.TextField(blank=True, null=True)

    def __unicode__(self):
        safedate = ''
        if self.date:
            safedate = self.date.strftime('%m/%d/%y') + ', '
        return '%s$%s to %s' % (safedate, self.amount, self.payee)


class Quote(models.Model):

    quote = models.TextField()
    source = models.CharField(max_length=128, blank=True, null=True)
    occasion = models.CharField(max_length=256, blank=True, null=True)

    def __unicode__(self):
        return '%s...' % self.quote[0:64]


class Agent(models.Model):

    name = models.CharField(max_length=128)
    agency = models.CharField(max_length=128, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = USStateField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(verbose_name="Zip", max_length=20, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)
    ssn = models.CharField(verbose_name="SSN/EIN", max_length=16, blank=True, null=True)

    def __unicode__(self):
        agency = ', %s' % self.agency if self.agency else ''
        return '%s%s' % (self.name, agency)


class CommissionPayment(models.Model):
    show = models.ForeignKey(Show, related_name="commission_payment", blank=True, null=True)
    agent = models.ForeignKey(Agent, related_name="commission_payment", blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    check_no = models.IntegerField(blank=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        unique_together = (('show', 'agent'),)
        ordering = ['-show__date']

    def __unicode__(self):
        agent = str(self.agent.name) if self.agent else '',
        show = str(self.show.venue) if self.show.venue else '',
        date = self.show.date.strftime('%m/%d/%y') if self.show else '',
        return '%s for %s on %s' % (agent[0], show[0], date[0])


class ProductionCompany(models.Model):

    name = models.CharField(max_length=128)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = USStateField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(verbose_name="Zip", max_length=20, blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)
    ssn = models.CharField(verbose_name="SSN/EIN", max_length=16, blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Production companies'


class ProductionCategory(models.Model):
    name = models.CharField(max_length=128)
    tax_category = models.ForeignKey(TaxExpenseCategory, related_name="production_category", blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Production categories'


class ProductionPayment(models.Model):
    show = models.ForeignKey(Show, related_name="production_payment", blank=True, null=True)
    company = models.ForeignKey(ProductionCompany, related_name="production_payment")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    check_no = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(ProductionCategory, blank=True, null=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['show__date']

    def __unicode__(self):
        company = str(self.company.name) if self.company else ''
        show = self.show
        cat = self.category
        return '%s for %s (%s)' % (company, show, cat)

    @property
    def payee(self):
        return self.company

    @property
    def new_category(self):
        return self.category

apps/fidouche/forms.py
from django import forms
from fidouche.widgets import AdminImageWidget
from shows.models import Show
from fidouche.models import Payment, SubPayment, Expense, TourExpense, \
    ProductionPayment, Income


FINANCIAL_FIELDS = (
    'attendance',
    'payer',
    'payee_check_no',
    'gross',
    'gross_method',
    'gross_itemized',
    'fee',
    'food_buyout',
    'travel_buyout',
    'lodging_buyout',
    'other_buyout',
    'commission',
    'agent',
    'commission_percentage',
    'commission_withheld',
    'commission_check_no',
    'commission_paid',
    'sound_cost',
    'in_ears_cost',
    'in_ears_check_no',
    'print_ship_cost',
    'ads_cost',
    'other_cost',
    'net',
    'payout',
    'to_account',
    'subs',
    'costs_itemized',
    'settlement_sheet',
    'payout_notes'
)
EXPENSE_FIELDS = (
    'date',
    'payee',
    'new_category',
    'amount',
    'check_no',
    'notes'
)
INCOME_FIELDS = (
    'date',
    'payer',
    'amount',
    'check_no',
    'notes'
)
TOUR_EXPENSE_FIELDS = (
    'date',
    'payee',
    'category',
    'amount',
    'check_no',
    'notes'
)
PRODUCTION_FIELDS = (
    'company',
    'amount',
    'check_no',
    'category',
)


class GigFinanceForm(forms.ModelForm):
    class Meta:
        model = Show
        fields = FINANCIAL_FIELDS
        widgets = {
            'settlement_sheet': AdminImageWidget()
        }

    def __init__(self, *args, **kwargs):
        super(GigFinanceForm, self).__init__(*args, **kwargs)
        for field in FINANCIAL_FIELDS:
            if field not in ['settlement_sheet', 'commission_paid']:
                self.fields[field].widget.attrs['class'] = 'form-control'


class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        # widgets = {
        #     'receipt_img': AdminImageWidget()
        # }

    def __init__(self, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)
        for field in INCOME_FIELDS:
            self.fields[field].widget.attrs['class'] = 'form-control input-sm'
        self.fields['date'].widget.attrs['data-format'] = 'YYYY-MM-DD'


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        widgets = {
            'receipt_img': AdminImageWidget()
        }
        fields = EXPENSE_FIELDS

    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        for field in EXPENSE_FIELDS:
            self.fields[field].widget.attrs['class'] = 'form-control input-sm'
        self.fields['date'].widget.attrs['data-format'] = 'YYYY-MM-DD'


class TourExpenseForm(forms.ModelForm):
    class Meta:
        model = TourExpense
        widgets = {
            'receipt_img': AdminImageWidget()
        }
        fields = TOUR_EXPENSE_FIELDS

    def __init__(self, *args, **kwargs):
        super(TourExpenseForm, self).__init__(*args, **kwargs)
        for field in TOUR_EXPENSE_FIELDS:
            self.fields[field].widget.attrs['class'] = 'form-control input-sm'
        self.fields['date'].widget.attrs['data-format'] = 'YYYY-MM-DD'


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        exclude = []
    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        self.fields['member'].widget.attrs['class'] = 'form-control input-sm'
        self.fields['amount'].widget.attrs['class'] = 'form-control input-sm'


class SubPaymentForm(forms.ModelForm):
    class Meta:
        model = SubPayment
        exclude = []
    def __init__(self, *args, **kwargs):
        super(SubPaymentForm, self).__init__(*args, **kwargs)
        self.fields['sub'].widget.attrs['class'] = 'form-control input-sm'
        self.fields['amount'].widget.attrs['class'] = 'form-control input-sm'


class ProductionPaymentForm(forms.ModelForm):
    class Meta:
        model = ProductionPayment
        exclude = []

    def __init__(self, *args, **kwargs):
        super(ProductionPaymentForm, self).__init__(*args, **kwargs)
        for field in PRODUCTION_FIELDS:
            if field == 'amount':
                self.fields[field].widget.attrs['class'] = 'form-control input-sm production-cost'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control input-sm'

apps/fidouche/templates/fidouche/dashboard.html
{% extends 'base_fidouche.html' %}
{% load custom_tags %}
{% load humanize %}

{% block content %}
<div class="page-header">
    {% if request.user.is_staff %}
    	<h2>Foreverland Finance Fidoucheboard</h2>
    {% else %}
    	<h2>Foreverland Finances</h2>
	{% endif %}
</div>
<div class="row">
	{% if request.user.is_staff %}
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Crunch some numbers</h3>
			</div>
			<div class="panel-body">
				<p>Most recent gig: <a href="{% url 'gig_finances' last_show.id %}">{{ last_show }} <i class="fa fa-angle-right"></i></a></p>
				<p>Next gig: <a href="{% url 'gig_finances' next_show.id %}">{{ next_show }} <i class="fa fa-angle-right"></i></a></p>
				<label class="sr-only" for="gSearch">Find a gig (current year)</label>
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-search"></i></span>
					<input type="text" class="form-control" id="gSearch" placeholder="Find a gig (current year)">
				</div>
			</div>
		</div>
	</div>
	{% endif %}
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">{% now "Y" %} year-to-date <small>includes gigs played before {% now "SHORT_DATETIME_FORMAT" %}</small></h3>
			</div>
			<div class="panel-body panel-no-pad">
				<table class="table table-striped">
					<tr>
						<td>Gigs booked:</td><td>{{ ytd.gigs_booked }}</td>
					</tr>
					<tr>
						<td>Gigs played:</td><td>{{ ytd.gigs_played }}</td>
					</tr>
					<tr>
						<td>Gross:</td><td>${{ ytd.gross|intcomma }} </td>
					</tr>
					<tr>
						<td>Net:</td><td>${{ ytd.net|intcomma }}</td>
					</tr>
					<tr>
						<td>Per player:</td><td>${{ ytd.payout|intcomma }}</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>
<table class="table table-striped table-bordered datatable">
	<thead>
		<tr>
			<th>Sort Date</th>
			<th>Date</th>
			<th>Venue</th>
			<th>Tour</th>
			<th>Attendance</th>
			<th>Gross</th>
			<th>Commission</th>
			<th>Total Expenses</th>
			<th>Net</th>
			<th>Per Player</th>
		</tr>
	</thead>
	<tbody>
	{% for gig in gigs %}
		<tr>
			<td>{{ gig.date|date:"Ymd" }}</td>
			<td><a href="{% if request.user.is_staff %}{% url 'gig_finances' gig.id %}{% else %}{% url 'gig_finances_view' gig.id %}{% endif %}">{{ gig.date|date:"n/j/y" }}</a></td>
			<td><a href="{% if request.user.is_staff %}{% url 'gig_finances' gig.id %}{% else %}{% url 'gig_finances_view' gig.id %}{% endif %}">{{ gig.venue }}</a> {% if not gig.public %}<span class="label label-success">private</span>{% endif %}{% if request.user.is_staff %}<a href="{% url 'gig_finances_view' gig.id %}" class="pull-right"><i class="fa fa-eye"></i></a>{% endif %}</td>
			<td>{% if gig.tour %}<a href="{% url 'tour_detail' gig.tour.id %}">{{ gig.tour }}</a>{% endif %}</td>
			<td>{% if gig.attendance %}{{ gig.attendance }}{% endif %}</td>
			<td>{% if gig.gross %}${{ gig.gross|intcomma }}{% else %}--{% endif %}</td>
			<td>{% if gig.commission %}${{ gig.commission|intcomma }} <small>({{ gig.commission_percentage }}%)</small>{% else %}0{% endif %}</td>
			<td>{% if gig.total_expenses %}${{ gig.total_expenses|floatformat:2|intcomma}} <i class="fa fa-list-ul expense-detail-toggle" data-toggle="collapse" data-target="#gig{{ gig.id }}_expenses"></i>
				<div id="gig{{ gig.id }}_expenses" class="collapse">
					<table class="table table-condensed expense-details">
						{% for k, v in gig.production_costs.items %}
							{% if v > 0 %}
								<tr><th>{{k}}:</th><td>${{v|intcomma}}</td></tr>
							{% endif %}
						{% endfor %}
						{% for k, v in gig.expenses.items %}
							{% if v > 0 %}
								<tr><th>{{k|title}}:</th><td>${{v|intcomma}}</td></tr>
							{% endif %}
						{% endfor %}
						{% if gig.tour.expenses %}
							<tr><th>Tour:</th><td>${{ gig.tour.expense_share|floatformat:2|intcomma }}</td></tr>
						{% endif %}
					</table>
				</div>{% endif %}
			</td>
			<td>{% if gig.net %}${{ gig.net|intcomma }}{% else %}--{% endif %}</td>
			<td>{% if gig.payout %}${{ gig.payout|intcomma }}{% else %}--{% endif %}{% if gig.payout_notes %}<i class="fa fa-comment payout-notes-toggle" data-toggle="collapse" data-target="#gig{{ gig.id }}_notes"></i>{% endif %}
				{% if gig.payout_notes %}
					<div id="gig{{ gig.id }}_notes" class="collapse payout-notes">
						{{ gig.payout_notes }}
					</div>
				{% endif %}
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
<blockquote class="qotd">
	<p><span>&ldquo;</span> {{ quote.quote|safe }} <span>&rdquo;</span></p>
	{% if quote.source or quote.occasion %}
		<footer>
			{% if quote.source %}{{ quote.source }}{% endif %}{% if quote.occasion %}, <cite>{{ quote.occasion }}</cite>{% endif %}
		</footer>
	{% endif %}
</blockquote>
{% endblock %}
{% block js %}
<script>
	$(function(){
		gTable = $('.datatable').dataTable({
			"sDom": "t<'row'<'col-md-6 dt-info'i><'col-md-6 dt-pagination'p>>",
			"iDisplayLength": 100,
			"bLengthChange": false,
			"aoColumnDefs": [
				{"bVisible": false, "aTargets": [0]},
				{"asSorting": ["asc"], "aTargets": [0]},
				{"iDataSort": 0, "aTargets": [1]},
				{"sType": "currency", "aTargets": [4,5,6,7,8]},
			],
		});
		$('#gSearch').keyup(function(){
			gTable.fnFilter($(this).val());
		});
	});
</script>
{% endblock %}

apps/fidouche/templates/fidouche/expense_create.html
{% extends 'base_fidouche.html' %}
{% load custom_tags %}

{% block content %}
<div class="page-header">
    <h2>File Expense</h2>
</div>
<form method="post" action="{{ request.path }}" role="form" enctype="multipart/form-data">{% csrf_token %}
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<fieldset>
				<div class="form-group">
					<label for="id_date">Date</label>
					<div id="expense_date_picker" class="input-group">
						{{ form.date }}
						<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="id_payee">Payee</label>
					{{ form.payee }}
				</div>
				<div class="form-group">
					<label for="id_category">Category</label>
					{{ form.new_category }}
				</div>
				<div class="form-group">
					<label for="id_category">Amount</label>
					<div class="input-group">
						<span class="input-group-addon">$</span>
						{{ form.amount }}
					</div>
				</div>
				<div class="form-group">
					<label for="id_category">Check #</label>
					{{ form.check_no }}
				</div>
				<div class="form-group">
					<label for="id_category">Notes</label>
					{{ form.notes }}
				</div>
				<div class="form-group">
					<label for="id_receipt_img"><i class="fa fa-camera"></i> Upload Receipt</label>
					{{ form.receipt_img }}
				</div>
    		</fieldset>
    	</div>
     	<button type="submit" class="btn btn-block btn-lg btn-primary">Save</button>
	</div>
</form>
{% endblock %}
{% block js %}
<script>
	$(function(){
		$('#expense_date_picker').datetimepicker({
			pickTime: false
		});
	});
</script>
{% endblock %}

apps/fidouche/templates/fidouche/gig_dashboard.html
{% extends 'base_fidouche.html' %}
{% load custom_tags %}

{% block content %}
        <h2>Gigs in {{ year }}</h2>
        <p><em>There are {{ this_years_gigs|length }} gigs in the database for this year.</em></p>
		<select name="gigselect" class="form-control input-lg">
			{% for gig in this_years_gigs %}
				<option val="{{ gig.id }}">{{ gig }}</option>
			{% endfor %}
		</select>
{% endblock %}

apps/fidouche/templates/fidouche/income_details.html
{% extends 'base_fidouche.html' %}
{% load custom_tags %}

{% block content %}
<div class="page-header">
	<h4>Income Details</h4>
    <h2>{{ income.date|date:"n/j/y" }}, ${{ income.amount }} from {{ income.payer }}</h2>
</div>
<form method="post" action="{{ request.path }}" role="form" enctype="multipart/form-data">{% csrf_token %}
	<div class="row">
		<div class="col-md-6 col-sm-6">
			<fieldset>
				<div class="form-group">
					<label for="id_date">Date</label>
					<div id="income_date_picker" class="input-group">
						{{ form.date }}
						<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="id_payee">Payer</label>
					{{ form.payer }}
				</div>
				<div class="form-group">
					<label for="id_amount">Amount</label>
					<div class="input-group">
						<span class="input-group-addon">$</span>
						{{ form.amount }}
					</div>
				</div>
				<div class="form-group">
					<label for="id_category">Check #</label>
					{{ form.check_no }}
				</div>
				<div class="form-group">
					<label for="id_category">Notes</label>
					{{ form.notes }}
				</div>
    		</fieldset>
    	</div>
     	<button type="submit" class="btn btn-block btn-lg btn-primary">Save</button>
	</div>
</form>
{% endblock %}
{% block js %}
<script>
	$(function(){
		$('#income_date_picker').datetimepicker({
			pickTime: false
		});
	});
</script>
{% endblock %}